/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XskribaAmbulanceWlList {
    }
}
declare global {
    interface HTMLXskribaAmbulanceWlListElement extends Components.XskribaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXskribaAmbulanceWlListElement: {
        prototype: HTMLXskribaAmbulanceWlListElement;
        new (): HTMLXskribaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xskriba-ambulance-wl-list": HTMLXskribaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XskribaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xskriba-ambulance-wl-list": XskribaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xskriba-ambulance-wl-list": LocalJSX.XskribaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXskribaAmbulanceWlListElement>;
        }
    }
}
